# DOCKER_IMAGE_TAG: stable
VCPU_USER_LIMIT: 1.5
VCPU_USER_GUARANTEE: 1
RAM_USER_LIMIT: 3G
RAM_USER_GUARANTEE: 2G
PLACEHOLDER_PODS: 3
IMAGE_PULL_SECRET_ENABLED: true
REGISTRY_USERNAME: _json_key
REGISTRY_EMAIL: dummy@example.com
IMAGE_PULL_SECRET: pullSecret
