apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: jhub
  name: pv-volume-shared
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: '/{{FILESTORE_NAME}}'
    server: '{{FILESTORE_IP_ADDRESS}}'
